name: CI

on:
  push:
    branches:
      - main # Production branch
      - develop # Development branch
    tags:
      - 'v*' # Trigger for version tags (e.g., v1.0.0)
      - 'release-*' # Matches tags like release-1.0, release-1
      - 'prod-*' # Matches tags like prod-2025-01-01
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run build
        run: npm run build

  deploy-production:
    needs: lint-and-build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/prod-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production (Vercel)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: npx vercel --prod --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID --confirm

  deploy-development:
    needs: lint-and-build
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/release-') || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Development (Vercel)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: npx vercel --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID --confirm
